#!/bin/bash
# Quick WhatsApp Mock Testing Commands

echo "=== WhatsApp Mock Mode Quick Test ==="
echo ""

BASE_URL="http://localhost:3000"
VERIFY_TOKEN="retoquei-webhook-secret"

echo "1. Testing Webhook Verification (GET)"
echo "Command:"
echo "curl -v '$BASE_URL/api/webhooks/whatsapp?hub.mode=subscribe&hub.verify_token=$VERIFY_TOKEN&hub.challenge=test-challenge'"
echo ""
echo "Expected: 200 status with response body: 'test-challenge'"
echo ""

echo "2. Testing Webhook Event Reception (POST)"
echo "Command:"
echo "curl -X POST '$BASE_URL/api/webhooks/whatsapp' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'x-idempotency-key: test-1' \\"
echo "  -d '{\"object\": \"whatsapp_business_account\", \"entry\": [{\"id\": \"123\", \"changes\": [{\"value\": {\"messaging_product\": \"whatsapp\", \"metadata\": {\"display_phone_number\": \"5511999999999\", \"phone_number_id\": \"1234\"}}, \"field\": \"messages\"}]}]}'"
echo ""
echo "Expected: 200 status with response: '{\"status\": \"ok\"}'"
echo ""

echo "3. Testing QR Code Endpoint (requires auth)"
echo "Note: You need to be logged in and have a workspace"
echo "Command:"
echo "curl -v '$BASE_URL/api/whatsapp/qr' \\"
echo "  -H 'Cookie: <your-auth-cookies>'"
echo ""
echo "Expected: 200 status with JSON containing 'base64' and 'code' fields"
echo ""

echo "4. Testing Status Endpoint (requires auth)"
echo "Note: You need to be logged in and have a workspace"
echo "Command:"
echo "curl -v '$BASE_URL/api/whatsapp/status' \\"
echo "  -H 'Cookie: <your-auth-cookies>'"
echo ""
echo "Expected: 200 status with mockMode: true"
echo ""

echo "=== Configuration Check ==="
echo ""
echo "Make sure your .env.local contains:"
echo "  WHATSAPP_MOCK_MODE=true"
echo "  WHATSAPP_WEBHOOK_VERIFY_TOKEN=retoquei-webhook-secret"
echo ""
